### ISSUE TITLE
compile error: Platform 'esp32-patched:esp32' not found

### ISSUE THREAD

**Issue by markma** [arduino/uno-r4-wifi-usb-bridge#59]
Help! When I run compile.sh, there comes an error shows that "Platform 'esp32-patched:esp32' not found: platform not installed". How can I fix it?

`arduino-cli compile -e --config-file arduino-cli.yaml --fqbn=esp32-patched:esp32:arduino_unor4wifi_usb_bridge:JTAGAdapter=default,PSRAM=disabled,FlashMode=qio,FlashSize=4M,LoopCore=1,EventsCore=1,USBMode=default,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,PartitionScheme=unor4wifi,CPUFreq=240,UploadSpeed=921600,DebugLevel=none,EraseFlash=none -v UNOR4USBBridge`

```
Error during build: Platform 'esp32-patched:esp32' not found: platform not installed
Platform esp32-patched:esp32 is not found in any known index
Maybe you need to add a 3rd party URL?
```

**Comment by pennam** [comment]
@markma did you get all the needed submodules https://github.com/arduino/uno-r4-wifi-usb-bridge?tab=readme-ov-file#update-submodules and the toolchain?

**Comment by markma** [comment]
1. `git submodule update --init --depth 1 --no-single-branch` not work.

```
usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] (--all| [--] <path>...)
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository>] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>][commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
   or: git submodule [--quiet] absorbgitdirs [--] [<path>...]
```

 I tried `git submodule update --init `. It worked.

2. I got the toolchain.

![image](https://github.com/user-attachments/assets/792c4720-7e6e-4486-b259-c162891fe03e)

**Comment by markma** [comment]
I move esp32-patched to "C:\Users\username\AppData\Local\Arduino15\packages" ， then compile.sh worked，but there ccomes another erro:
`"C:\\Users\\username\\AppData\\Local\\Arduino15\\packages\\esp32-patched\\esp32/tools/gen_esp32part.exe" -q "C:\\Users\\username\\AppData\\Local\\Temp\\arduino\\sketches\\C54DD7BA064F9074EB02856D69247C51/partitions.csv" "C:\\Users\\username\\AppData\\Local\\Temp\\arduino\\sketches\\C54DD7BA064F9074EB02856D69247C51/UNOR4USBBridge.ino.partitions.bin"
Error at line 3: Value 'undefined' is not valid. Known keywords: esphttpd, phy, efuse, nvs, fat, spiffs, ota, coredump, nvs_keys
`
![image](https://github.com/user-attachments/assets/615d51ba-5754-4c1f-960e-55f422217307)

**Comment by pennam** [comment]
replace undefined with 0x06 https://github.com/arduino/uno-r4-wifi-usb-bridge/issues/21
